services:
  - type: web
    name: personal-fin-tracker
    env: python
    buildCommand: ""
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
