# ───────────────────────── render.yaml ─────────────────────────
services:
  - type: web
    name: personal-fin-tracker
    env: python
    region: oregon           # or whatever region you chose

    buildCommand: |
      ./build.sh             # runs flake8 + pytest, fails build on error

    startCommand: |
      ./start.sh             # runs migrate + gunicorn

    envVars:
      # ─── Django core ─────────────────────────────────────────
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings_ci       # we’ve been using the CI/Prod settings
      - key: SECRET_KEY
        sync: false                   # fill in via the UI
      - key: DEBUG
        value: "False"

      # ─── Database  (Render Postgres OR external) ────────────
      - fromDatabase:
          name: personal-fin-tracker-db   # Render DB name
          property: connectionString
        key: DATABASE_URL

      # ─── Optional: allow tests that hit external APIs, etc. ─
      # - key: API_TOKEN
      #   sync: false

databases:
  - name: personal-fin-tracker-db
    region: oregon
    plan: free

jobs:
  - type: cron
    name: post-recurring
    env: python
    schedule: "0 5 * * *"      # 05:00 UTC daily
    command: |
      PYTHONUNBUFFERED=1 DJANGO_SETTINGS_MODULE=core.settings \
      python manage.py post_recurring
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
