# Generated by Django 4.2.23 on 2025-08-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="note",
        ),
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional free-text note shown to the user",
                max_length=255,
            ),
        ),
    ]
