# Generated by Django 4.2.23 on 2025-08-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_budget_budget_unique_budget_per_period"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={"get_latest_by": "modified"},
        ),
        migrations.RemoveConstraint(
            model_name="budget",
            name="unique_budget_per_period",
        ),
        migrations.AlterField(
            model_name="budget",
            name="period",
            field=models.CharField(
                choices=[("W", "Weekly"), ("M", "Monthly"), ("Y", "Yearly")],
                default="M",
                max_length=1,
            ),
        ),
    ]
