# Generated by Django 4.2.23 on 2025-08-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_alter_budget_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterField(
            model_name="budget",
            name="period",
            field=models.CharField(choices=[("M", "Monthly"), ("Y", "Yearly")], default="M", max_length=1),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(fields=("user", "category", "period"), name="unique_budget_per_period"),
        ),
    ]
