# Generated by Django 4.2.23 on 2025-08-08 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0007_transfer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="destination_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_transfers",
                to="finance.category",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="source_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outgoing_transfers",
                to="finance.category",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
