# Generated by Django 4.2.23 on 2025-08-09 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_alter_transfer_destination_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="finance.transfer",
            ),
        ),
    ]
