# Generated by Django 4.2.23 on 2025-08-09 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_transfer_transfer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="finance.transfer",
            ),
        ),
    ]
