# Generated by Django 4.2.23 on 2025-08-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_alter_transfer_transfer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="debt",
            options={"get_latest_by": "modified"},
        ),
        migrations.RemoveField(
            model_name="debt",
            name="category",
        ),
        migrations.RemoveField(
            model_name="debt",
            name="interest_rate",
        ),
        migrations.RemoveField(
            model_name="debt",
            name="minimum_payment",
        ),
        migrations.RemoveField(
            model_name="debt",
            name="opened_date",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="memo",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="transfer",
        ),
        migrations.AddField(
            model_name="payment",
            name="note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="finance.transfer",
            ),
        ),
        migrations.AlterField(
            model_name="debt",
            name="name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="destination_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfers_in",
                to="finance.category",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="source_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfers_out",
                to="finance.category",
            ),
        ),
    ]
