# Generated by Django 4.2.23 on 2025-08-09 07:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_alter_debt_options_remove_debt_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="debt",
            options={"ordering": ("-created",)},
        ),
        migrations.RemoveField(
            model_name="payment",
            name="note",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="transfer",
        ),
        migrations.AddField(
            model_name="debt",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finance.category",
            ),
        ),
        migrations.AddField(
            model_name="debt",
            name="interest_rate",
            field=models.DecimalField(decimal_places=2, default=1, help_text="% per annum", max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="debt",
            name="minimum_payment",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="debt",
            name="opened_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="memo",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="transfer",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="finance.transfer",
            ),
        ),
        migrations.AlterField(
            model_name="debt",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="description",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="destination_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_transfers",
                to="finance.category",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="source_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outgoing_transfers",
                to="finance.category",
            ),
        ),
    ]
