# Generated by Django 4.2.23 on 2025-08-09 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_alter_debt_options_remove_payment_note_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transfer",
            name="transfer",
        ),
        migrations.AddField(
            model_name="transaction",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="finance.transfer",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="destination_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfers_in",
                to="finance.category",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="source_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfers_out",
                to="finance.category",
            ),
        ),
    ]
