name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: finance_user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: finance_test_db
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://finance_user:password@localhost:5432/finance_test_db
      SECRET_KEY: dummy                             # Django needs something
      # any other envs (JWT, email) go here

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run migrations
        run: python manage.py migrate --noinput

      - name: Run tests & collect coverage
        run: pytest --cov=.

      # Optional: send coverage to Codecov
      - uses: codecov/codecov-action@v4
        if: ${{ success() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
